// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('myApp.abcd', []).factory('myF', function() {
    return {
      'say': function() {
        return console.log(11);
      }
    };
  });

}).call(this);

//# sourceMappingURL=test1.js.map
